package response

// Legacy service errors are localized at the HTTP boundary, without changing
// persisted audit records or coupling repositories to a request language.
var messageKeys = map[string]string{
	"API 不存在":                            "api.apiDoesNotExist",
	"API 路径和方法已存在":                       "api.anApiWithThisPathAndMethod",
	"API不存在":                             "api.apiDoesNotExist.6a1993",
	"create notice failed":               "api.unableToCreateNotice",
	"created":                            "api.createdSuccessfully",
	"endAt must be greater than startAt": "api.theEndTimeMustBeAfterThe",
	"file is required":                   "api.selectAFileToUpload",
	"get my notices failed":              "api.unableToLoadYourNotices",
	"get notice list failed":             "api.unableToLoadNotices",
	"invalid request":                    "api.invalidRequestParameters",
	"invalid targetType":                 "api.invalidRecipientType",
	"invalid username or password":       "api.incorrectUsernameOrPassword",
	"login successful":                   "api.signedInSuccessfully",
	"mark read failed":                   "api.unableToMarkNoticeAsRead",
	"no valid receiver found":            "api.noValidRecipientsFound",
	"ok":                                 "api.success",
	"token 已禁用":                          "api.theTokenIsDisabled",
	"token 已过期":                          "api.theTokenHasExpired",
	"token 无权访问该 API":                    "api.thisTokenCannotAccessThisApi",
	"不能删除基础管理员":                          "api.theBaseAdministratorCannotBeDeleted",
	"令牌已失效":                              "api.theTokenIsNoLongerValid",
	"会话已失效，请重新登录":                        "api.yourSessionHasExpiredPleaseSignIn",
	"保存":                                 "api.savedSuccessfully",
	"修改后的API路径和方法已存在":                    "api.anApiWithThisPathAndMethod.c1d6ca",
	"入参错误":                               "api.invalidParameters",
	"公开注册未开启，请联系管理员":                     "api.registrationIsClosedContactAnAdministrator",
	"切换失败":                               "api.unableToSwitchRoles",
	"创建失败":                               "api.createFailed",
	"创建成功":                               "api.createdSuccessfully.7fd87d",
	"删除失败":                               "api.deleteFailed",
	"删除成功":                               "api.deletedSuccessfully",
	"参数校验失败":                             "api.parameterValidationFailed",
	"参数绑定失败":                             "api.invalidRequestParameters.7241b3",
	"参数错误":                               "api.invalidParameters.3e64ed",
	"基础管理员必须保持启用及管理员角色": "api.theBaseAdministratorMustRemainEnabledAnd",
	"头像上传失败":                    "api.avatarUploadFailed",
	"存在无效的 API 选择":              "api.oneOrMoreSelectedApisDoNot",
	"存在相同路径和方法的API":             "api.anApiWithThisPathAndMethod.289bf7",
	"您未拥有该角色权限":                 "api.youHaveNotBeenAssignedThisRole",
	"成功":                        "api.success.51991a",
	"找不到资源":                     "api.resourceNotFound",
	"授权已过期":                     "api.authorizationHasExpired",
	"操作失败":                      "api.operationFailed",
	"文件上传失败":                    "api.fileUploadFailed",
	"无效的令牌":                     "api.invalidToken",
	"无效的用户状态":                   "api.invalidUserStatus",
	"无法获取用户角色信息, 请重新登录":         "api.unableToLoadYourRolePleaseSign",
	"更新失败":                      "api.updateFailed",
	"更新成功":                      "api.updatedSuccessfully",
	"更新权限失败":                    "api.unableToUpdatePermissions",
	"更新用户资料失败":                  "api.unableToUpdateTheUserProfile",
	"服务内部错误":                    "api.internalServerError",
	"服务繁忙，请稍后重试 (Breaker Open)": "api.theServiceIsBusyPleaseTryAgain",
	"未授权，请登录":                   "api.pleaseSignInToContinue",
	"未选择数据":                     "api.selectAtLeastOneItem",
	"未选择要删除的 token":             "api.selectATokenToDelete",
	"权限不足":                      "api.accessDenied",
	"此用户已经被禁用":                  "api.thisAccountIsDisabled",
	"此菜单存在子菜单，不可删除":             "api.removeChildMenusBeforeDeletingThisMenu",
	"此角色存在子角色，不可删除":             "api.removeChildRolesBeforeDeletingThisRole",
	"此角色有用户正在使用，不可删除":           "api.thisRoleIsAssignedToUsersAnd",
	"注册失败，请稍后重试":                "api.registrationFailedPleaseTryAgainLater",
	"注销失败，请重试":                  "api.unableToSignOutPleaseTryAgain",
	"注销成功":                      "api.signedOutSuccessfully",
	"添加失败":                      "api.addFailed",
	"添加成功":                      "api.addedSuccessfully",
	"父菜单不存在":                    "api.theParentMenuDoesNotExist",
	"父角色不存在":                    "api.theParentRoleDoesNotExist",
	"用户不存在":                     "api.userDoesNotExist",
	"用户名已存在":                    "api.usernameAlreadyExists",
	"用户名或密码错误":                  "api.incorrectUsernameOrPassword.3ef442",
	"策略引用了不存在的 API":             "api.thePolicyReferencesAnApiThatDoes",
	"策略格式无效":                    "api.invalidPolicyFormat",
	"管理员角色不可删除":                 "api.theAdministratorRoleCannotBeDeleted",
	"系统内部错误":                    "api.internalServerError.468f6a",
	"获取Token失败":                 "api.unableToIssueAToken",
	"获取列表失败":                    "api.unableToLoadTheList",
	"获取失败":                      "api.unableToLoadData",
	"获取成功":                      "api.loadedSuccessfully",
	"获取用户信息失败":                  "api.unableToLoadUserInformation",
	"获取菜单失败":                    "api.unableToLoadMenus",
	"获取菜单数据失败":                  "api.unableToLoadMenuData",
	"获取详情失败":                    "api.unableToLoadDetails",
	"菜单不存在":                     "api.menuDoesNotExist",
	"菜单不能形成循环":                  "api.menuHierarchyCannotContainCycles",
	"菜单路径已存在":                   "api.menuPathAlreadyExists",
	"要更新的角色不存在":                 "api.theRoleToUpdateDoesNotExist",
	"角色ID不能为空":                  "api.roleIdIsRequired",
	"角色ID已存在":                   "api.roleIdAlreadyExists",
	"角色不存在":                     "api.roleDoesNotExist",
	"角色不能是自身的父角色":               "api.aRoleCannotBeItsOwnParent",
	"角色仍被使用":                    "api.thisRoleIsStillInUse",
	"角色无效":                      "api.invalidRole",
	"设置失败":                      "api.unableToSaveSettings",
	"设置成功":                      "api.settingsSaved",
	"访问过于频繁，请稍后再试":              "api.tooManyRequestsPleaseTryAgainLater",
	"请先删除子菜单":                   "api.removeChildMenusFirst",
	"请先删除子角色":                   "api.removeChildRolesFirst",
	"请至少选择一个 API":               "api.selectAtLeastOneApi",
	"请至少选择一个角色":                 "api.selectAtLeastOneRole",
	"请选择要上传的图片":                 "api.selectAnImageToUpload",
	"请选择要上传的文件":                 "api.selectAFileToUpload.face48",
	"路由Path已存在":                 "api.routePathAlreadyExists",
	"路由Path已存在，请更换":             "api.routePathAlreadyExistsChooseAnotherPath",
	"过期时间必须晚于当前时间":              "api.expirationMustBeInTheFuture",
	"过期时间格式错误":                  "api.invalidExpirationDate",
	"配置保存失败":                    "api.unableToSaveConfiguration",
	"配置参数错误":                    "api.invalidConfigurationParameters",
	"重置失败":                      "api.resetFailed",
	"重置成功":                      "api.resetSuccessfully",
}
