import { createStyles } from 'antd-style';

export const useStyles = createStyles(({ token }) => ({
  stack: { display: 'grid', gap: 24 },
  hero: {
    overflow: 'hidden',
    border: `1px solid ${token.colorBorderSecondary}`,
    borderRadius: 16,
    background: `linear-gradient(115deg, ${token.colorBgContainer} 25%, ${token.colorPrimaryBg} 100%)`,
  },
  welcome: {
    padding: '30px 34px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 24,
    '@media (max-width: 700px)': { padding: 24 },
  },
  eyebrow: {
    color: token.colorTextSecondary,
    fontSize: 12,
    letterSpacing: 2,
    marginBottom: 14,
  },
  greeting: {
    fontSize: 28,
    fontWeight: 600,
    lineHeight: 1.4,
    margin: '0 0 10px',
    overflowWrap: 'anywhere',
    '@media (max-width: 700px)': { fontSize: 23 },
  },
  muted: { color: token.colorTextSecondary, fontSize: 13, lineHeight: 1.8 },
  calendar: {
    flexShrink: 0,
    width: 160,
    display: 'flex',
    alignItems: 'center',
    gap: 15,
    color: token.colorPrimary,
    '& strong': { fontSize: 48, fontWeight: 500, lineHeight: 1 },
    '& span': { fontSize: 12, lineHeight: 1.9 },
    '@media (max-width: 700px)': { display: 'none' },
  },
  summary: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    borderTop: `1px solid ${token.colorBorderSecondary}`,
    background: token.colorBgContainer,
    '@media (max-width: 550px)': { gridTemplateColumns: '1fr' },
  },
  metric: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    padding: '20px 30px',
    minWidth: 0,
    '& + &': { borderLeft: `1px solid ${token.colorBorderSecondary}` },
    '& strong': {
      fontSize: 22,
      fontWeight: 600,
      lineHeight: 1.4,
      overflowWrap: 'anywhere',
    },
    '@media (max-width: 550px)': {
      padding: '16px 24px',
      '& + &': {
        borderLeft: 0,
        borderTop: `1px solid ${token.colorBorderSecondary}`,
      },
    },
  },
  icon: {
    display: 'grid',
    placeItems: 'center',
    flexShrink: 0,
    width: 42,
    height: 42,
    borderRadius: 12,
    background: token.colorPrimaryBg,
    color: token.colorPrimary,
    fontSize: 21,
  },
  columns: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 2fr) minmax(280px, 1fr)',
    gap: 24,
    alignItems: 'start',
    '@media (max-width: 1050px)': { gridTemplateColumns: '1fr' },
  },
  panel: {
    minWidth: 0,
    border: `1px solid ${token.colorBorderSecondary}`,
    borderRadius: 12,
    background: token.colorBgContainer,
    padding: 24,
    '@media (max-width: 550px)': { padding: 20 },
  },
  sectionTitle: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginBottom: 20,
    '& h2': { margin: 0, fontSize: 16, fontWeight: 600 },
  },
  links: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 12,
    '@media (max-width: 700px)': {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
    '@media (max-width: 360px)': { gridTemplateColumns: '1fr' },
  },
  quickLink: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 10,
    minWidth: 0,
    padding: '16px 18px',
    borderRadius: 10,
    border: `1px solid ${token.colorBorderSecondary}`,
    color: token.colorText,
    transition: 'border-color .2s, background .2s',
    '&:hover': {
      borderColor: token.colorPrimaryBorder,
      background: token.colorFillAlter,
      color: token.colorText,
    },
    '&:focus-visible': {
      outline: `2px solid ${token.colorPrimary}`,
      outlineOffset: 3,
    },
    '& strong': { fontSize: 14, fontWeight: 500, overflowWrap: 'anywhere' },
    '& small': {
      color: token.colorTextSecondary,
      fontSize: 12,
      lineHeight: 1.6,
    },
    '@media (max-width: 550px)': { padding: 14 },
  },
  linkTop: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    '& > .anticon': { color: token.colorTextQuaternary, fontSize: 12 },
  },
  linkIcon: {
    display: 'grid',
    placeItems: 'center',
    height: 32,
    width: 32,
    borderRadius: 8,
    background: token.colorPrimaryBg,
    color: token.colorPrimary,
    fontSize: 17,
  },
  noticeMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
    paddingBottom: 14,
    color: token.colorTextSecondary,
    fontSize: 12,
    borderBottom: `1px solid ${token.colorBorderSecondary}`,
  },
  notice: {
    padding: '18px 0',
    borderBottom: `1px solid ${token.colorBorderSecondary}`,
    minWidth: 0,
  },
  noticeHeading: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    marginBottom: 8,
    '& h3': {
      margin: 0,
      fontSize: 14,
      fontWeight: 500,
      overflowWrap: 'anywhere',
    },
  },
  unreadDot: {
    display: 'inline-block',
    width: 6,
    height: 6,
    background: token.colorPrimary,
    borderRadius: '50%',
    flexShrink: 0,
  },
  noticePreview: {
    color: token.colorTextSecondary,
    fontSize: 13,
    lineHeight: 1.8,
    overflow: 'hidden',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflowWrap: 'anywhere',
    margin: '0 0 8px',
  },
  noticeFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    color: token.colorTextTertiary,
    fontSize: 12,
  },
  empty: {
    minHeight: 210,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    gap: 12,
    '& h3': { fontSize: 15, fontWeight: 500, margin: 0 },
  },
  emptyIcon: {
    display: 'grid',
    placeItems: 'center',
    height: 64,
    width: 64,
    fontSize: 28,
    color: token.colorPrimary,
    background: token.colorPrimaryBg,
    borderRadius: 20,
    marginBottom: 4,
  },
  pagination: { display: 'flex', justifyContent: 'flex-end', marginTop: 18 },
  health: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    color: token.colorSuccess,
    fontWeight: 500,
    padding: '14px 16px',
    borderRadius: 8,
    background: token.colorSuccessBg,
    marginBottom: 8,
  },
  service: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: '13px 0',
    borderBottom: `1px solid ${token.colorBorderSecondary}`,
    fontSize: 13,
    '& .ant-tag': { margin: 0 },
  },
  serviceName: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    '& .anticon': { color: token.colorTextSecondary, fontSize: 16 },
  },
  panelFooter: {
    marginTop: 20,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
    fontSize: 12,
    color: token.colorTextSecondary,
  },
  account: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    marginBottom: 20,
    '& strong': { display: 'block', fontWeight: 500, overflowWrap: 'anywhere' },
  },
  accountFacts: {
    display: 'grid',
    gap: 14,
    margin: 0,
    '& div': { display: 'flex', justifyContent: 'space-between', gap: 14 },
    '& dt': { color: token.colorTextSecondary, fontSize: 13, flexShrink: 0 },
    '& dd': {
      margin: 0,
      fontSize: 13,
      overflowWrap: 'anywhere',
      textAlign: 'right',
    },
  },
  noticeBody: {
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
    lineHeight: 1.9,
    padding: '16px 0',
    maxHeight: '55vh',
    overflowY: 'auto',
  },
}));
