FROM golang:1.25.2-alpine AS builder

WORKDIR /app
ENV GOPROXY=https://goproxy.cn,direct

RUN apk add --no-cache gcc musl-dev

COPY . .

RUN go mod download
RUN go build -o plugin-market ./cmd/plugin-market

FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add tzdata ca-certificates

COPY --from=builder /app/plugin-market ./plugin-market
COPY --from=builder /app/configs ./configs

EXPOSE 18081

CMD ["./plugin-market", "-f", "./configs/plugin-market.yaml"]
