import { createStyles } from 'antd-style';

export const useStyles = createStyles(({ token }) => ({
  page: { display: 'grid', gap: 30, paddingBottom: 8, color: token.colorText },
  hero: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.3fr) minmax(280px, 1fr)',
    gap: 44,
    padding: '38px 40px',
    alignItems: 'center',
    overflow: 'hidden',
    border: `1px solid ${token.colorBorderSecondary}`,
    borderRadius: 16,
    background: `linear-gradient(115deg, ${token.colorBgContainer} 35%, ${token.colorPrimaryBg} 100%)`,
    '@media (max-width: 1100px)': { gap: 28, padding: 28 },
    '@media (max-width: 800px)': { gridTemplateColumns: '1fr', padding: 24 },
  },
  intro: {
    minWidth: 0,
    '& h1': {
      margin: '18px 0 10px',
      fontSize: 36,
      fontWeight: 650,
      lineHeight: 1.25,
      letterSpacing: -1,
      overflowWrap: 'anywhere',
    },
    '@media (max-width: 550px)': { '& h1': { fontSize: 30 } },
  },
  eyebrow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    color: token.colorPrimaryText,
    fontSize: 13,
    fontWeight: 500,
  },
  brandMark: {
    display: 'grid',
    placeItems: 'center',
    width: 30,
    height: 30,
    borderRadius: 9,
    background: token.colorPrimaryBg,
    fontSize: 18,
  },
  subtitle: {
    margin: '0 0 14px',
    fontSize: 18,
    fontWeight: 500,
    lineHeight: 1.6,
  },
  description: {
    margin: 0,
    maxWidth: 530,
    color: token.colorTextSecondary,
    lineHeight: 1.9,
    fontSize: 14,
  },
  actions: { marginTop: 24 },
  branch: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    marginTop: 22,
    color: token.colorTextSecondary,
    fontSize: 12,
    '& code': {
      padding: '3px 9px',
      borderRadius: 6,
      color: token.colorText,
      background: token.colorFillAlter,
      fontSize: 12,
    },
  },
  architecture: {
    minWidth: 0,
    maxWidth: 420,
    width: '100%',
    justifySelf: 'center',
  },
  diagramHeading: {
    marginBottom: 14,
    fontSize: 12,
    color: token.colorTextSecondary,
    letterSpacing: 1,
  },
  extension: {
    padding: '18px 20px',
    border: `1px dashed ${token.colorPrimaryBorder}`,
    borderRadius: 12,
    background: token.colorBgContainer,
    '& p': {
      margin: '10px 0 0',
      fontSize: 12,
      lineHeight: 1.7,
      color: token.colorTextSecondary,
    },
  },
  layerHeading: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    fontSize: 14,
    '& > .anticon': { color: token.colorPrimaryText, fontSize: 16 },
    '& strong': { fontWeight: 600 },
    '& > span:last-child:not(.anticon)': {
      marginLeft: 'auto',
      fontSize: 11,
      color: token.colorTextSecondary,
    },
  },
  connector: {
    display: 'grid',
    placeItems: 'center',
    height: 26,
    color: token.colorPrimaryText,
    fontSize: 14,
  },
  coreLayer: {
    padding: '18px 20px',
    borderRadius: '12px 12px 0 0',
    border: `1px solid ${token.colorPrimaryBorder}`,
    background: token.colorBgContainer,
  },
  moduleList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 7,
    marginTop: 14,
    '& span': {
      border: `1px solid ${token.colorBorderSecondary}`,
      borderRadius: 6,
      padding: '5px 9px',
      fontSize: 12,
      color: token.colorTextSecondary,
    },
  },
  foundationLayer: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '13px 20px',
    background: token.colorPrimaryBg,
    border: `1px solid ${token.colorPrimaryBorder}`,
    borderTop: 0,
    borderRadius: '0 0 12px 12px',
    color: token.colorPrimaryText,
    fontSize: 12,
    lineHeight: 1.7,
  },
  diagramCaption: {
    margin: '12px 0 0',
    textAlign: 'center',
    color: token.colorTextSecondary,
    fontSize: 12,
    lineHeight: 1.7,
  },
  sectionHeading: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 16,
    marginBottom: 18,
    '& h2': { margin: 0, fontSize: 18, fontWeight: 600, lineHeight: 1.5 },
    '& p': {
      margin: '5px 0 0',
      color: token.colorTextSecondary,
      fontSize: 13,
      lineHeight: 1.7,
    },
    '@media (max-width: 550px)': {
      alignItems: 'flex-start',
      flexDirection: 'column',
      gap: 8,
    },
  },
  sectionNote: { color: token.colorTextSecondary, fontSize: 12, flexShrink: 0 },
  capabilityGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 14,
    '@media (max-width: 1100px)': {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
    '@media (max-width: 650px)': { gridTemplateColumns: '1fr' },
  },
  capability: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 14,
    minWidth: 0,
    padding: 22,
    border: `1px solid ${token.colorBorderSecondary}`,
    borderRadius: 12,
    background: token.colorBgContainer,
    '& h3': {
      fontSize: 14,
      fontWeight: 600,
      margin: '1px 0 8px',
      lineHeight: 1.6,
    },
    '& p': {
      color: token.colorTextSecondary,
      fontSize: 13,
      lineHeight: 1.8,
      margin: 0,
    },
    '@media (max-width: 550px)': { padding: 20 },
  },
  icon: {
    display: 'grid',
    placeItems: 'center',
    flexShrink: 0,
    width: 38,
    height: 38,
    borderRadius: 10,
    background: token.colorPrimaryBg,
    color: token.colorPrimaryText,
    fontSize: 19,
  },
  details: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.25fr) minmax(0, 1fr)',
    gap: 20,
    '@media (max-width: 1000px)': { gridTemplateColumns: '1fr' },
  },
  panel: {
    minWidth: 0,
    padding: 26,
    border: `1px solid ${token.colorBorderSecondary}`,
    borderRadius: 12,
    background: token.colorBgContainer,
    '@media (max-width: 550px)': { padding: 20 },
  },
  techList: { display: 'grid' },
  techRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
    padding: '16px 0',
    '& + &': { borderTop: `1px solid ${token.colorBorderSecondary}` },
    '&:last-child': { paddingBottom: 0 },
    '@media (max-width: 650px)': {
      alignItems: 'flex-start',
      flexDirection: 'column',
      gap: 12,
    },
  },
  techLabel: {
    display: 'flex',
    gap: 12,
    alignItems: 'center',
    minWidth: 130,
    flexShrink: 0,
    '& > span': { color: token.colorTextSecondary, fontSize: 20 },
    '& h3': { fontSize: 13, fontWeight: 500, margin: 0 },
    '& p': {
      color: token.colorTextSecondary,
      fontSize: 12,
      margin: '4px 0 0',
      lineHeight: 1.6,
    },
  },
  tags: {
    display: 'flex',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    gap: 6,
    margin: 0,
    padding: 0,
    listStyle: 'none',
    '& li': {
      fontSize: 12,
      color: token.colorTextSecondary,
      padding: '4px 8px',
      background: token.colorFillAlter,
      borderRadius: 5,
      overflowWrap: 'anywhere',
    },
    '@media (max-width: 650px)': { justifyContent: 'flex-start' },
  },
  resourceList: { display: 'grid', gap: 8 },
  resource: {
    display: 'grid',
    gridTemplateColumns: '32px minmax(0, 1fr) 14px',
    alignItems: 'center',
    gap: 12,
    padding: '14px 12px',
    borderRadius: 8,
    color: token.colorText,
    transition: 'background .15s',
    '&:hover': {
      color: token.colorPrimaryText,
      background: token.colorFillAlter,
    },
    '&:focus-visible': {
      outline: `2px solid ${token.colorPrimary}`,
      outlineOffset: 2,
    },
    '& strong': { display: 'block', fontSize: 14, fontWeight: 500 },
    '& small': {
      display: 'block',
      marginTop: 5,
      fontSize: 12,
      lineHeight: 1.7,
      color: token.colorTextSecondary,
    },
    '& > .anticon:last-child': {
      color: token.colorTextSecondary,
      fontSize: 12,
    },
  },
  resourceIcon: { color: token.colorTextSecondary, fontSize: 20 },
  resourceNote: {
    display: 'flex',
    gap: 10,
    marginTop: 18,
    paddingTop: 18,
    borderTop: `1px solid ${token.colorBorderSecondary}`,
    color: token.colorTextSecondary,
    fontSize: 12,
    lineHeight: 1.7,
  },
}));
